# Build settings
permalink   : /blog/:year/:title/
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Rachel Berry
description: "Perpetual student of all things tech"
keywords: "blog, jekyll, women in tech, engineer, github"
url: http://cmrberry.com
baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/cmrberry/cmrberry.github.io

# Author settings
author:
  name      : Rachel Berry
  job       : Analytics Engineer at GitHub
  bio       : "Perpetual student of all things tech. Driven by data and copious amounts of coffee. Proud wife, mom, and Jew."
  thumb     : /img/author.jpg
  email     : cmrberry@gmail.com
  url       : http://cmrberry.com
  github    : http://github.com/cmrberry
  twitter   : http://twitter.com/cmrberry
  linkedin  : http://linkedin.com/in/cmrberry

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
