# Site settings
title: Rachel Berry
header-img: img/home-bg.jpg
description: "Rachel Berry"
baseurl: ""
url: "http://cmrberry.com"
twitter_username: cmrberry
github_username:  cmrberry

# Build settings
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
